name = "War Development Center"
author = "Coldfront15/Henderson"
prefix = "wdc"
mainprefix = "x"

[hemtt.build]
pdrive = "require"


[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE
    "2369477168", # Advanced Developer Tools 
    "3058335345", # TBD Mortars
    "3119699935", # SIMC LCD
    "1341387001",
    "1862880106",
    "3233638297", # m119
]

dlc = [
    "Spearhead 1944",
]
optionals = []
mission = "TESTACE_WDCERAAA.VR" # Mission to launch directly into the editor with
parameters = [
    "-skipIntro",           # These parameters are passed to the Arma 3 executable
    "-noSplash",            # They do not need to be added to your list
    "-showScriptErrors",    # You can add additional parameters here
    "-debug",
    "-filePatching",
]

executable = "arma3_x64" # Default: "arma3_x64"

[version]
major = 1 # Overrides path when set
minor = 0
patch = 1
build = 0 # Optional

git_hash = 4

[files]
include = [
    "mod.cpp",      # These files are copied to the build directory by default
    "meta.cpp",     # They do not need to be added to your list
    "LICENSE",
    "089_blauw_cal.paa",
    "089_ca.paa",
    "089_jellwick_ca.paa",
    "large - dev.paa",
    "large.paa",
]